version: "2"

services:
  # data volume container
  nginx-config:
    container_name: pythonwebapp_nginx_config
    image: cirros
    volumes:
      - /etc/conf
    command: /bin/true

  # service discovery
  interlock:
    container_name: pythonwebapp_interlock
    image: etoews/interlock
    command: -D run
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:8080"
    volumes_from:
      - nginx-config
      - container:swarm-data:ro

  # load balancer
  lb:
    container_name: pythonwebapp_lb
    image: nginx:1.9
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "interlock.ext.name=nginx"
    volumes_from:
      - nginx-config

  # app
  app:
    image: ehazlett/docker-demo:latest
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "interlock.hostname=test"
      - "interlock.domain=local"

networks:
  backend: {}
